### ISSUE TITLE
Support request with arrays

### ISSUE THREAD

**Issue by alexeev-igor** [ea-ae/required-value-types#2]
Thanks for your implementation, great job, very appreciated. But I guess this solution does not support arrays in request, for example.

Because method `FindElement` in `JsonValueProvider` throws exception when trying call `TryGetProperty`. Honestly, I'm trying to extend your solution and solve this problem, but not successful yet.

Anyway, thanks for this project.

```json
{
    "Data": [
        {
            "Status": 1,
            "Id": 123,
            "InnerData": [
                {
                    "Reason": 5
                },
                {
                    "Reason": 5,
                    "InnerId": 123
                }
            ]
        },
        {
            "Status": 1,
            "InnerData": [
                {
                    "Reason": 5,
                    "InnerId": 123
                },
                {
                    "Reason": 5
                }
            ]
        }
    ]
}
```

**Comment by alexeev-igor** [comment]
Realized that I should handle `JsonValueKind.Array` in `FindElement` method and return `new StringValues(array)`. Well, I guess :)

**Comment by ea-ae** [comment]
Hey, I can merge a PR with a fix if you ever feel like submitting one. Updated the README to reflect the limitation.

**Comment by alexeev-igor** [comment]
Yea, I will try :) By the way, JsonDocument is IDisposable and it has comment `Failure to properly Dispose this object will result in the memory not being returned to the pool, which will cause an increase in GC impact across various parts of the framework`, so it can be important for someone.

**Comment by ea-ae** [comment]
Yeah true, it'll delay the disposal which may slightly increase memory use. I'd fix it myself right now, but I don't have my dev environment on hand for testing 😅 Thanks for noticing!

**Comment by alexeev-igor** [comment]
Actually, I gave up with trying to support arrays. It seems kind a impossible in that way.
